### PR TITLE
cards view

### PR DESCRIPTION
**Pull request by li9ht**

### CODE REVIEW

**Comment by joevo2** [comment]
it works? OMG thanks man

**Comment by joevo2** [comment]
i think you modified the wrong branch it should be the dev branch

**Comment by joevo2** [comment]
I'm working on the card view in the dev branch instead of the master branch thanks a lot of your help i was really surprised and happy that someone is willing to help out :)

**Comment by li9ht** [comment]
welcome..  sorry i didnt notice your dev branch

**Comment by joevo2** [comment]
OMG it works nicely damn nice thanks a lot but do i need to do it in the recycler view? thanks a lot a lot for your help open source FTW :+1: can u help me look at the dev branch is killing me

**Comment by joevo2** [comment]
initially i thought i must do it in a recycler view, should i continue with the recycler view? or just use the array adapter with the card view in XML? :smile:

**Comment by li9ht** [comment]
I've tried recyler view before.. but its quite hard to implement.. so im back to array adapter and its been working fine... i suggest that you complete the app first with array adapter and then improve it with recycler view ..

**Comment by joevo2** [comment]
thanks a lot for your help can i add you on fb or something :smile:  btw wanna work on this project together :) you are a really kind person LOL like God sending Angel to help me :smile: thanks a lot a lot. didn't expect anyone to do a pull request. Whats the benefit of recycler view hmmmm

**Comment by joevo2** [comment]
btw can u help me take a look at my class Rescue I'm couldn't implement parcelable too

**Pull request merged**
